<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>DeferredReality.BridgeAdapter</RootNamespace>
    <AssemblyName>DeferredRealityFramework.BridgeAdapter</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <Import Project="..\RimWorldReferences.props" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="DeferredRealityFramework">
      <HintPath>..\..\1.6\Assemblies\DeferredRealityFramework.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="RimWorldDevBridge">
      <HintPath>..\..\..\RimWorldDevBridge\1.6\Assemblies\RimWorldDevBridge.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(DeferredRealityManagedPath)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
