<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>DeferredReality.Aquaculture</RootNamespace>
    <AssemblyName>DeferredReality.Aquaculture</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>true</Optimize>
    <OutputPath>..\..\..\..\AquacultureFishing\1.6\Assemblies\</OutputPath>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <PropertyGroup><DeferredRealityRequireHarmony>true</DeferredRealityRequireHarmony></PropertyGroup>
  <Import Project="..\..\..\DevTools\RimWorldReferences.props" />
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\AquacultureFishing\Source\AquacultureFishing.csproj" />
    <Reference Include="DeferredRealityFramework">
      <HintPath>..\..\..\1.6\Assemblies\DeferredRealityFramework.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(DeferredRealityManagedPath)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(DeferredRealityManagedPath)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(DeferredRealityHarmonyPath)</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
