<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>DeferredReality</RootNamespace>
    <AssemblyName>DeferredRealityFramework</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <DeferredRealityRequireHarmony>true</DeferredRealityRequireHarmony>
  </PropertyGroup>
  <Import Project="..\DevTools\RimWorldReferences.props" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>true</Optimize>
    <OutputPath>..\1.6\Assemblies\</OutputPath>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Adapters\**" />
    <EmbeddedResource Remove="Adapters\**" />
    <None Remove="Adapters\**" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(DeferredRealityManagedPath)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(DeferredRealityManagedPath)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(DeferredRealityManagedPath)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(DeferredRealityManagedPath)\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(DeferredRealityHarmonyPath)</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
